### ISSUE TITLE
How to fix the error, while setting up Vapor and MySQL 8

### ISSUE THREAD

**Issue by ftitreefly** [PacktPublishing/Hands-On-Swift-5-Microservices-Development#2]
**Setting up Vapor and the database**

Swift 5.2-dev + Vapor 4 + MySQL 8

.env
`MYSQL_CRED='mysql://service_users:password@192.168.31.185:3306/service_users?ssl=false'`

When run `./Run migrate`,  errors show:

> Migrate Command: Prepare
> [ INFO ] query read _fluent_migrations
> [ ERROR ] MySQL error: A secure connection to the server is required for authentication.
> 
> Fatal error: Error raised at top level: MySQL error: A secure connection to the server is required for authentication.: file /Users/buildnode/jenkins/workspace/oss-swift-5.2-package-osx/swift/stdlib/public/core/ErrorType.swift, line 200
> 2020-03-25 01:37:24.168029+0800 Run[2189:60048] Fatal error: Error raised at top level: MySQL error: A secure connection to the server is required for authentication.: file /Users/buildnode/jenkins/workspace/oss-swift-5.2-package-osx/swift/stdlib/public/core/ErrorType.swift, line 200
> Program ended with exit code: 9

Thanks.

**Comment by jhoughjr** [comment]
try ssl=true.

**Comment by jhoughjr** [comment]
well doing that just yields ``` Migrate Command: Prepare
[ ERROR ] handshakeFailed(NIOSSL.BoringSSLError.sslError([Error: 268435581 error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED]))
Fatal error: Error raised at top level: NIOSSL.NIOSSLError.handshakeFailed(NIOSSL.BoringSSLError.sslError([Error: 268435581 error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED])): file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1103.8.25.8/swift/stdlib/public/core/ErrorType.swift, line 200
``` 
I really have no idea how to fix this.

**Comment by jhoughjr** [comment]
I am investigating whether -e require_secure_transport=OFF in the launch command fixes it. But it seem I'll have to destroy the container and repeat all those steps.

**Comment by proggeramlug** [comment]
Update on this issue: Either start via docker-compose, (see README about that). Or you need to add this flag when running MySQL: `--default-authentication-plugin=mysql_native_password`
