### ISSUE TITLE
PostgreSQL version

### ISSUE THREAD

**Issue by piersebdon** [PacktPublishing/Hands-On-Swift-5-Microservices-Development#4]
Seeing as Vapor recommends using PostgreSQL - I think it would make a big difference to the readers and Vapor community if you could provide the alternate commands for PostgreSQL. Switching the packages and using PostgreSQL models etc is pretty straight forward buts its the terminal commands that are the trickiest.

I am currently stuck on the code that sets up the three users and three databases on p113. Even using the mysql commands doesn't seem to work.

Really enjoying the book and I think this is a big opportunity for lots of people to get into Vapor due to the current world circumstances and having the PostgreSQL option would be awesome.
Thanks

**Comment by proggeramlug** [comment]
@piers12 Postgre has been added for Chapter 7. Additional chapter coming too! :)

Check the README for updates!
