### ISSUE TITLE
Only accessToken ?

### ISSUE THREAD

**Issue by saroar** [PacktPublishing/Hands-On-Swift-5-Microservices-Development#7]
is it rit only send back accessToken?

https://github.com/PacktPublishing/Hands-On-Swift-5-Microservices-Development/blob/a0994613bc1a673b976aed3aa1786cb0f24b7875/Chapter%207/UserService-Postgres/Sources/App/Controllers/AuthController.swift#L117

**Comment by packt-pradeeps** [comment]
Hello @saroar ,
Please elaborate the issue you are facing.

**Comment by saroar** [comment]
the issue is when you send a request for new access token you should get also access token + refresh token

**Comment by calebkleveter** [comment]
@saroar Yes, this is correct. Since you are only refreshing the access token, you only need the new access token, not a new refresh token. Once the refresh token expires, the user should log in again.
